# Generated by Django 3.1.6 on 2021-02-19 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
